### ISSUE TITLE
3.3.1 release contains print statement in django middleware

### ISSUE THREAD

**Issue by coagulant** [opbeat/opbeat_python#115]
Could you please remove print statement, because it appears in production logs.
I couldn't find it in [git history](https://github.com/opbeat/opbeat_python/commits/master/opbeat/contrib/django/middleware/__init__.py) however.

Also, releasing opbeat as a python wheel would be nice.

```
$ wget https://pypi.python.org/packages/32/cc/cb773012072a03f786698ac801bd86d9b9712c79bfbd1dd4e505986c235f/opbeat-3.3.1.tar.gz\#md5\=547678b2237aaa7a6190dba7dc1800d4
$ tar xzf opbeat-3.3.1.tar.gz
$ grep "print" opbeat-3.3.1/opbeat/contrib/django/middleware/__init__.py -C 10 -n
```

```
160-                        request._opbeat_view_func
161-                    )
162-                else:
163-                    transaction_name = ''
164-
165-                status_code = response.status_code
166-                transaction_name = build_name_with_http_method_prefix(
167-                    transaction_name,
168-                    request
169-                )
170:                print (transaction_name)
171-
172-                self.client.end_transaction(transaction_name, status_code)
173-        except Exception:
174-            self.client.error_logger.error(
175-                'Exception during timing of request',
176-                exc_info=True,
177-            )
178-        return response
179-
180-
```

**Comment by piquadrat** [comment]
Thanks for the heads-up and sorry about the trouble! We just shipped an updated version to pypi, 3.3.2, which doesn't have the said print statement.

As for wheels, we are working on that. Due to the fact that we have a binary component to our module, shipping it as a wheel is not trivial. Since the last release, we automatically build binary [manylinux](https://www.python.org/dev/peps/pep-0513/l) wheels, but don't upload them to PyPI yet due to its somewhat experimental nature. Binary wheels for this release should be available in ~1 hour at https://github.com/opbeat/opbeat_python/releases/tag/3.3.2
