### ISSUE TITLE
Django 1.11 Support

### ISSUE THREAD

**Issue by alexandermeyer** [opbeat/opbeat_python#163]
Using Django 1.11, there is a crash without a stack trace when using runserver. This is with a Python 3.6 Docker image.

**Comment by beniwohli** [comment]
Thanks for reporting this! I'll have a closer look and try to replicate!

**Comment by beniwohli** [comment]
Hi @alexandermeyer. I tried to replicate this with a bare Django 1.11.2 project on Python 3.6, but didn't have any success. Also, we have a lot of users on Django 1.11 / Python 3.6 that don't experience this issue, so it's probably not a general Django 1.11 problem.

Can you help me with a couple questions?

1. When does your app crash, during startup, when the first request comes in, or after some time?
1. Does a traceback appear if you run your django command with `--traceback`?
1. Can you share your requirements.txt with me (either here, or by sending it to support@opbeat.com)?
1. Also, does the crash go away if you do one of these two things?
   * remove `'opbeat.contrib.django'` from `INSTALLED_APPS`
   * remove `'opbeat.contrib.django.middleware.OpbeatAPMMiddleware'` from `MIDDLEWARE`

**Comment by alexandermeyer** [comment]
@beniwohli Thanks for looking into this!

1. The app crashes as soon as I click into a model in the Django admin.
2. No traceback appears when running with `--traceback`; the container just shuts down.
3. I sent the requirements.txt to support@opbeat.com and referenced this issue.
4. When I remove `'opbeat.contrib.django'` from `INSTALLED_APPS`, it works as intended, which is why I thought it might be related to Opbeat. I understand that it might not be, but crossing off Opbeat would still be useful in debugging.

**Comment by beniwohli** [comment]
Thanks for the requirements file Ales, I'll have a closer look.

Meanwhile, the fact that it crashes when you go into the Django Admin gave me a (very possibly wrong) hunch: could it be that the machine where you're running the `runserver` command is somewhat memory-restricted? Running opbeat has some memory overhead, especially if a view has lots of traces (which can easily happen in the admin changelist). And the process being killed without a traceback could certainly be caused by an out-of-memory event.

**Comment by alexandermeyer** [comment]
It did have to do with memory! Adding `import threading; threading.stack_size(8*1000*1024)` to `manage.py` solved the issue.

Thanks for your help, @beniwohli.
