### ISSUE TITLE
Flask client : logging option log "info" level as error

### ISSUE THREAD

**Issue by nMustaki** [opbeat/opbeat_python#66]
Hi,

So with logging=True, if I do app.logger.info("test"), it is sent back to Opbeat server and tagged as error. I expected only "error" and "exception" messages to be sent ?
I relevant, here my logging initialization code : 
```python
    file_handler = RotatingFileHandler(
        app.config["LOG_FILENAME"], 'a', 100 * 1024 * 1024, 2)
    file_handler.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s'))
    file_handler.setLevel(logging.DEBUG)
    app.logger.setLevel(logging.DEBUG)
    app.logger.addHandler(file_handler)
```

Thanks

**Comment by roncohen** [comment]
Hey @nMustaki. By default, the handler will pick everything up. I want to change it to only WARN or more severe.

In the meantime, check out the "fine-grained" example here: https://opbeat.com/docs/articles/get-started-with-flask/#logging
It explicitly adds the handler and filters out everything below WARN. You can do that instead of `logging=True`.

**Comment by nMustaki** [comment]
So I will, thanks !
