### ISSUE TITLE
Broken APM django middleware

### ISSUE THREAD

**Issue by koutoftimer** [opbeat/opbeat_python#73]
Steps to reproduce: 
1. Example setup https://opbeat.com/docs/articles/get-started-with-django/#setup
2. `pip install opbeat>=3.0.4` 
3. Run development server

```
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/usr/local/lib/python3.4/dist-packages/opbeat/contrib/django/middleware/__init__.py", line 71, in process_request_wrapper
    response = wrapped(*args, **kwargs)
TypeError: process_request() takes 1 positional argument but 2 were given
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python3.4/dist-packages/opbeat/contrib/django/middleware/__init__.py", line 83, in process_response_wrapper
    response = wrapped(*args, **kwargs)
TypeError: process_response() takes 2 positional arguments but 3 were given
[08/Oct/2015 14:07:27]"GET / HTTP/1.1" 500 68677
```

With version `3.0.2` everything works fine.

**Comment by piquadrat** [comment]
@koutoftimer thanks for the report! Could it be that any of the middleware classes you use have the `@staticmethod` decorator on `process_request` or `process_response`?

If that's the case and there are no pressing reasons for those methods to be static, I suggest to remove that decorator and make the methods "normal" instance methods (this is the interface suggested by Django).

If that's not an option, you can disable our instrumentation of middlewares by updating the `OPBEAT` configuration dictionary like this:

    OPBEAT = {
        # other settings
        'INSTRUMENT_DJANGO_MIDDLEWARE': False,
    }

By disabling instrumentation of middleware, we lose insight into code paths where the response is generated by a middleware and not a view. One example is Django's `CommonMiddleware`, which creates `HttpResponseRedirect` responses due to the `APPEND_SLASH` setting (https://docs.djangoproject.com/en/1.8/ref/middleware/#module-django.middleware.common). The rest of the Performance insights are unaffected by this setting. 

We're looking into detecting this case automatically in the future.

**Comment by koutoftimer** [comment]
> Could it be that any of the middleware classes you use have the @staticmethod decorator on process_request or process_response?

Yes, I have middleware with `@staticmethod` decorator. I'm lucky, it is under my control. Thank you for fast response.
